CREATE TABLE RECIPES(
	-- need autoincrement because I cannot reuse ids when one is deleted
	id 			INTEGER PRIMARY KEY AUTOINCREMENT,
	name 		TEXT NOT NULL,
	author		TEXT,
	description	TEXT NOT NULL,
	method		TEXT NOT NULL,
	image		TEXT,
	type		INTEGER DEFAULT 0 CHECK(type >= 0 AND type <= 3),
	CREATED_AT	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE INGREDIENTS(
	-- with no autoincrement, keys may be reused, but for this case its fine
	id			INTEGER PRIMARY KEY,
	name		TEXT NOT NULL UNIQUE
);

CREATE TABLE RECIPE_INGREDIENTS(
	recipe		INTEGER NOT NULL,
	ingredient	INTEGER NOT NULL,
	amount		REAL,
	unit		TEXT,
	sort		INTEGER,
	FOREIGN KEY(recipe) REFERENCES RECIPES(id) ON DELETE CASCADE,
	FOREIGN KEY(ingredient) REFERENCES INGREDIENTS(id)
);

CREATE TRIGGER update_timestamp_trigger
AFTER UPDATE ON RECIPES
BEGIN
	UPDATE RECIPES SET UPDATED_AT = STRFTIME('%Y-%m-%d %H:%M:%S', 'NOW') WHERE id = NEW.id;
END;
