CREATE TABLE IF NOT EXISTS RECIPES(
	ID 		INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME 	VARCHAR NOT NULL,
	AUTHOR	VARCHAR NOT NULL,
	DESCRIPTION	TEXT NOT NULL,
	INGREDIENTS	JSON NOT NULL,
	METHOD	TEXT NOT NULL,
	IMAGE	VARCHAR DEFAULT "noimage.jpeg"
);