CREATE TABLE IF NOT EXISTS RECIPES(
	id 			INTEGER PRIMARY KEY AUTOINCREMENT,
	name 		VARCHAR NOT NULL,
	author		VARCHAR NOT NULL,
	description	TEXT NOT NULL,
	ingredients	JSON NOT NULL,
	method		TEXT NOT NULL,
	image		VARCHAR DEFAULT "noimage.jpeg",
	CREATED_AT	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);